All kinds of improvements & new features
eddiewebb/flarum-calendar pull request #48
Opened 2023-05-17 13:59 UTC by iPurpl3x

We (at @glowingblue) would love to use this extension in a productive environment and to do that, we took the time to update this extension's implementation to meet our quality standards.

The main changes in this PR are:
- Use the TextEditor component provided by Flarum to write the details of an event
- Add missing translation keys
- Admin can now optionally hide the event host (default: show)
- Lots of bug-fixes
- Lots of updates to deprecated code
- General code cleanup
- Code formatting (prettier...)
- Dynamically load external libraries, to reduce bundle size
- and much more...

We hope this PR will get accepted and merged into the main repo. Also, if possible, we would love to get special rights on the main repo, to be able to help with maintaining this extension and be able to quickly release any bug-fixes that might be required in the future.

2023-05-17 18:51 UTC, eddiewebb commented
🙏  very grateful and will look this over today!

2023-05-17 18:58 UTC, eddiewebb reviewed
Code changes look good. I've been lacking on any CI for this repo so will pull down for local validation tonight.

2023-05-17 18:58 UTC, eddiewebb commented on js/dist/forum.js.LICENSE.txt
> +/*! regenerator-runtime -- Copyright (c) 2014-present, Facebook, Inc. -- license (MIT): https://github.com/facebook/regenerator/blob/main/LICENSE */
Not sure about this..

2023-05-17 18:58 UTC, eddiewebb commented on js/src/forum/utils/dynamicallyLoadLib.js
> +const libs = {
Brilliant! shrinks size WAYYYYY down!

2023-05-17 18:59 UTC, eddiewebb requested changes
Qualify FB generator usage if required to keep license here.

2023-05-19 11:10 UTC, eddiewebb approved these changes
local testing looks good will merge and tag.

2023-05-19 11:13 UTC, merged

2023-05-19 11:21 UTC, eddiewebb commented
https://packagist.org/packages/webbinaro/flarum-calendar as 1.6.0

2023-05-23 08:02 UTC, iPurpl3x commented
Cool, thanks for merging and releasing my changes @eddiewebb !